apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes
type: application
version: 2.1.0
appVersion: 0.13.2
dependencies:
  - name: external-dns
    version: 6.13.2
    repository: https://charts.bitnami.com/bitnami/
